version: '4'

services:

  m2-php:
    container_name: m2-php
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - appdata:/var/www
      - ./src:/var/www/magento246:cached
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=magento246"

  m2-nginx:
    container_name: m2-nginx
    image: nginx:1.22
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/magento246:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/m2-config/nginx.conf:/var/www/nginx.conf
    depends_on:
      - m2-php

  m2-db:
    container_name: m2-mariadb
    image: mariadb:10.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  m2-redis:
    container_name: m2-redis
    image: redis:latest

  m2-rabbit:
    container_name: m2-rabbit
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  m2-elasticsearch:
    image: elasticsearch:7.17.12
    container_name: m2-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      "discovery.type": "single-node"

volumes:
  appdata:
